name: buildfork
on :
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v4
      - name: cache
        uses: actions/cache@v4.0.0
        with:
          path: ~/.npm
          key: buildcache
      - run: npm ci
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Upload code coverage
        uses: actions/upload-artifacts@v4.3.1
        with:
          name: codecoverage
          path: coverage
      - name: build
        run: npm run build
      - name: Upload build files
        uses: actions/upload-artifacts@v4.3.1
        with:
          name: build
          path: build
          
